site_name: Fatalyst's web site
site_url: https://fatalyst.dev/
site_description: Fatalyst's projects
repo_name: mr-fatalyst/fatalyst.dev
repo_url: https://github.com/mr-fatalyst/fatalyst.dev

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
    - icons
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
    logo: fontawesome/solid/code

nav:
  - index.md
  - FastOpenAPI:
    - " ": fastopenapi/index.md
    - "Back": index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mr-fatalyst
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/nikita-ryzhenkov
    - icon: fontawesome/solid/envelope
      link: mailto:nikita.ryzhenkoff@gmail.com
